pipeline {

    agent any

    environment {
        IMAGE_NAME = "nextjs-app"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'master', url: 'https://github.com/saimudunuri09/calculator_app.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'npm run test || true'   // skip if no tests
            }
        }

        stage('Build Next.js App') {
            steps {
                sh 'npm run build'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh """
                    docker build -t ${IMAGE_NAME}:${BUILD_NUMBER} .
                    docker tag ${IMAGE_NAME}:${BUILD_NUMBER} ${IMAGE_NAME}:latest
                """
            }
        }

        stage('Deploy') {
            steps {
                script {

                    sh """
                        docker stop nextjs-container || true
                        docker rm nextjs-container || true

                        docker run -d \
                            -p 3000:3000 \
                            --name nextjs-container \
                            nextjs-app:latest
                    """
                }
            }
        }
    }

    post {
        success {
            echo "🚀 Deployment Successful!"
            echo "App running at: http://localhost:3000"
        }
    }
}
