pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'master', url: 'https://github.com/saimudunuri09/Git_document'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'npm test || echo "No tests found"'
            }
        }

        stage('Build Next.js App') {
            steps {
                sh 'npm run build'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t nextjs-app .'
            }
        }

        stage('Deploy Locally') {
            steps {
                script {

                    def PORT = ""
                    def CONTAINER_NAME = ""

                    if (ENVIRONMENT == "dev1") { PORT = "5001"; CONTAINER_NAME = "nextjs-dev1" }
                    if (ENVIRONMENT == "dev2") { PORT = "5002"; CONTAINER_NAME = "nextjs-dev2" }
                    if (ENVIRONMENT == "dev3") { PORT = "5003"; CONTAINER_NAME = "nextjs-dev3" }

                    sh """
                        docker stop ${CONTAINER_NAME} || true
                        docker rm ${CONTAINER_NAME} || true
                        docker run -d -p ${PORT}:3000 --name ${CONTAINER_NAME} nextjs-app
                    """

                    echo "APP RUNNING: http://localhost:${PORT}"
                }
            }
        }
    }
}
